chore: use pr_url from steps outputs

diff --git a/release/sync/action.yml b/release/sync/action.yml
--- a/release/sync/action.yml
+++ b/release/sync/action.yml
@@ -57,9 +57,10 @@ runs:
         AUTHOR=$(gh release view $TAG --json author -q '.author.login')
         echo "release author: $AUTHOR"
 
-        # This just checks that the user exists, if the release could not be found the AUTHOR
-        # would be "release not found" which is a non-existant user.
-        [$(gh api -X GET search/users -f q=$AUTHOR) == "0"] && echo "Could not find author" && exit 1;
+        # # This just checks that the user exists, if the release could not be found the AUTHOR
+        # # would be "release not found" which is a non-existant user.
+        # [$(gh api -X GET search/users -f q=$AUTHOR) == "0"] && echo "Could not find author" && exit 1;
+        # FIXME: the output from github changed so we need to fix how we check for user existence
 
         echo "Creating chore/sync-release-$TAG from release branch"
         git fetch origin $TO_BRANCH:$TO_BRANCH $FROM_BRANCH:$FROM_BRANCH
@@ -87,6 +88,7 @@ runs:
         BOARD_NUMBER: ${{ inputs.board_number }}
         COLUMN_FIELD: ${{ inputs.column_field }}
         COLUMN_NAME: ${{ inputs.column_name }}
+        PR_URL: ${{ steps.create_pull.outputs.PR_URL }}
       shell: bash
       run: |
         FIELD_QUERY=".fields[] | select(.name==\"$COLUMN_FIELD\") | .id"
